services:
  mongo:
    image: mongo:5
    ports:  
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mern

  social-be:
    build:
      context: ./Social-Media-Web-App-Mern-Stack-/Server/
      dockerfile: DockerFile
    ports:
      - "2053:4000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/hik8
    networks:
      - mern

  chat-be:
    build:
      context: ./mern-chat-app/backend/
      dockerfile: DockerFile
    ports:
      - "8443:5000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/hik8
    networks:
      - mern

  social-fe:
    build:
      context: ./Social-Media-Web-App-Mern-Stack-/client/
      dockerfile: DockerFile
    ports:
      - "80:80"
    container_name: social-fe
    networks:
      - mern

volumes:
  mongo-data:
networks:
  mern: