services:
  mongo:
    image: mongo:5
    ports:  
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mern

  social-be:
    build:
      context: ./Social-Media-Web-App-Mern-Stack-/Server/
      dockerfile: DockerFile
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/hik8
    container_name: socialBe
    networks:
      - mern

  chat-be:
    build:
      context: ./mern-chat-app/backend/
      dockerfile: DockerFile
    ports:
      - "8443:443"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/hik8
    container_name: chatBe
    networks:
      - mern
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - mern
  social-fe:
    build:
      context: ./Social-Media-Web-App-Mern-Stack-/client/
      dockerfile: DockerFile
    ports:
      - "81:3000"
    container_name: social-fe
    networks:
      - mern

volumes:
  mongo-data:
  redis-data:
networks:
  mern: