FROM node:20

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package.json ./
RUN npm install

# Copy source code
COPY . .

# Install Certbot and dependencies
RUN apt-get update && apt-get install -y \
    software-properties-common \
    certbot \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

# Expose port
EXPOSE 80

COPY run-certbot.sh /run-certbot.sh
COPY start.sh /start.sh
RUN chmod +x /run-certbot.sh /start.sh

# Start server
CMD ["/start.sh"]