# Use Node image
FROM node:20

# Set working directory
WORKDIR /app

# Copy source code
COPY . .

# Copy package files and install dependencies
COPY package.json ./
RUN npm install

# Remove package-lock.json if present
RUN rm -f package-lock.json

# Expose port
EXPOSE 4000

# Start server
CMD ["npx", "nodemon"]