# Use Node image
FROM node:20

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY ./package.json ./
RUN npm install

# Copy source code
COPY . .

# Expose port
EXPOSE 4000

# Start server
CMD ["npx", "nodemon"]